signform/urls.py
from django.urls import path

from .views import LoginView, SignUpView, IndexView, LogoutView

app_name = 'signform'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('index/', IndexView.as_view(), name='index'),
    path('logout/', LogoutView.as_view(), name='logout')
]

testapp/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('signform.urls', namespace='signform')),
    path('social-auth/', include('social_django.urls', namespace="social")),
]

signform/models.py
from django.db import models
from django.contrib.auth.models import User


class Subscribers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

signform/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.forms import UserCreationForm


class UserCreationFormWithSubscribe(UserCreationForm):
    subscribe_news = forms.BooleanField(required=False)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")
        field_classes = {'username': UsernameField}

signform/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views import View

from django.contrib.auth import login
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import AccessMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import UserCreationFormWithSubscribe
from .models import Subscribers


class NotLoginRequiredMixin(AccessMixin):
    """Verify that the current user is not authenticated."""
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(reverse('signform:index'))
        return super().dispatch(request, *args, **kwargs)


class SignUpView(NotLoginRequiredMixin, View):
    template_name = 'signform/forms/signup.html'

    def post(self, request):
        form = UserCreationFormWithSubscribe(data=request.POST)
        if form.is_valid():
            user = form.save()

            if form.cleaned_data.get('subscribe_news', False):
                Subscribers.objects.create(user=user)

            return redirect(reverse('signform:login'))

        return render(request, self.template_name, {'form': form})

    def get(self, request):
        form = UserCreationFormWithSubscribe()
        return render(request, self.template_name, {'form': form})


class LoginView(NotLoginRequiredMixin, View):
    template_name = 'signform/forms/login.html'

    def get(self, request):
        form = AuthenticationForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect(reverse('signform:index'))
        return render(request, self.template_name, {'form': form})


class LogoutView(LoginRequiredMixin, View):

    def post(self, request):
        logout(request)
        return redirect(reverse('signform:login'))


class IndexView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'signform/main.html', {'user': request.user})

signform/templates/signform/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'signforms/css/base.css' %}">
    <link rel="stylesheet" href="{% static 'signforms/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
<div class="container">
    {% block content %}{% endblock %}
</div>
<!--script-->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
<!--script-->
</body>
</html>

signform/templates/signform/forms/login.html
{% extends 'signform/base.html' %}
{% load widget_tweaks %}
{% block content %}
<div class="row h-100">
    <div class="col-sm-3 my-auto"></div>
    <div class="col-sm-6 my-auto">
        <div class="form">
            <p class="text-center text-uppercase">Log in</p>
            <div class="my-auto">
                <a href="{% url 'social:begin' 'facebook' %}" disabled>
                    <button type="button" class="btn btn-link" style="width:50%; float:left" disabled>
                        <div class="text-uppercase">
                            <i class="fab fa-facebook"></i> facebook
                        </div>
                    </button>
                </a>
                </button>
                <a href="{% url 'social:begin' 'google-oauth2' %}">
                    <button type="button" class="btn btn-link" style="width:50%">
                        <div class="text-uppercase">
                            <i class="fab fa-google"></i> google
                        </div>
                    </button>
                </a>
            </div>
            <div></div>
            <div class="separator text-lowercase text-center">or</div>
            <form method="post">
                {% csrf_token %}

                <div class="form-group">
                    {{form.username|add_class:"form-control"|attr:"placeholder:Username"}}
                </div>

                <div class="form-group">
                    {{form.password|add_class:"form-control"|attr:"placeholder:Password"}}

                    {% for error in form.password.errors %}
                    <small id="{{form.password.id_for_label}}_help" class="form-text" style="color: red">
                        {{error}}
                    </small>
                    {% endfor %}
                </div>

                <a href=""><button type="submit" class="btn btn-success text-uppercase" style="width: 100%; padding: 15px;">LOG IN</button></a>

            </form>

            <div style="padding-top:15px;">
                <a href="{% url 'signform:signup'%}">
                    <button type="button" class="btn btn-outline-primary" style="width: 100%;">REGISTER</button>
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm-3 my-auto"></div>
</div>
{% endblock %}

signform/templates/signform/forms/signup.html
{% extends 'signform/base.html' %}
{% load widget_tweaks %}
{% block content %}


<div class="row h-100">
    <div class="col-sm-3 my-auto"></div>
    <div class="col-sm-6 my-auto">
        <div class="form">
            <p class="text-center text-uppercase">Sign up with</p>
            <div class="my-auto">
                <a href="{% url 'social:begin' 'facebook' %}">
                    <button type="button" class="btn btn-link" style="width:50%; float:left" disabled>
                        <div class="text-uppercase">
                            <i class="fab fa-facebook"></i> facebook
                        </div>
                    </button>
                </a>
                </button>
                <a href="{% url 'social:begin' 'google-oauth2' %}">
                    <button type="button" class="btn btn-link" style="width:50%">
                        <div class="text-uppercase">
                            <i class="fab fa-google"></i> google
                        </div>
                    </button>
                </a>
            </div>
            <div></div>
            <div class="separator text-lowercase text-center">or</div>
            <form method="post" style="padding-top: 15px">
                {% csrf_token %}

                <div class="form-group">
                    {{form.username|add_class:"form-control"|attr:"placeholder:Username"}}

                    {% for error in form.username.errors %}
                    <small id="{{form.username.id_for_label}}_help" class="form-text" style="color: red">
                        {{error}}
                    </small>
                    {% endfor %}
                </div>

                <div class="form-group">
                    {{form.first_name|add_class:"form-control"|attr:"placeholder:First Name"}}
                </div>

                <div class="form-group">
                    {{form.last_name|add_class:"form-control"|attr:"placeholder:Last Name"}}
                </div>

                <div class="form-group">
                    {{form.email|add_class:"form-control"|attr:"placeholder:Email"}}

                    {% for error in form.email.errors %}
                    <small id="{{form.email.id_for_label}}_help" class="form-text" style="color: red">
                        {{error}}
                    </small>
                    {% endfor %}
                </div>

                <div class="form-group">
                    {{form.password1|add_class:"form-control"|attr:"placeholder:Password"}}

                    {% for error in form.password1.errors %}
                    <small id="{{form.password1.id_for_label}}_help" class="form-text" style="color: red">
                        {{error}}
                    </small>
                    {% endfor %}
                </div>


                <div class="form-group">
                    {{form.password2|add_class:"form-control"|attr:"placeholder:Confirm password"}}

                    {% for error in form.password2.errors %}
                    <small id="{{form.password2.id_for_label}}_help" class="form-text" style="color: red">
                        {{error}}
                    </small>
                    {% endfor %}
                </div>

                <div class="input-group mb-3">
                    <div class="form-check">
                        {{form.subscribe_news|add_class:"form-check-input"|attr:"id:subscribe_news"}}
                        <label class="form-check-label" for="subscribe_news">I'd like to receive news and offers</label>
                    </div>
                </div>

                <button type="submit" class="btn btn-success" style="width: 100%; padding: 15px;">REGISTER</button>

            </form>

            <div style="display: flow-root; margin-top: 16px;">
                <div style="float: left; padding-top: 5px;">Already have an account?</div>
                <a href="{% url 'signform:login'%}">
                    <button type="button" class="btn btn-outline-primary" style="float: right;">LOG IN</button>
                </a>
            </div>
        </div>
    </div>
    <div class="col-sm-3 my-auto"></div>
</div>


{% endblock %}

signform/templates/signform/main.html
{% extends 'signform/base.html' %}
{% load widget_tweaks %}
{% block content %}


<div class="row h-100">
    <div class="col-sm-3 my-auto"></div>
    <div class="col-sm-6 my-auto">
        <div class="form">
            Hello, {{user.username}}! You have successfully logged in.
            <form action="{% url 'signform:logout'%}" method="post" style="padding-top:15px;">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary">LOG OUT</button>
            </form>
        </div>
    </div>
    <div class="col-sm-3 my-auto"></div>
</div>


{% endblock %}